name: CI
run-name: ${{ github.actor }} is learning Github Actions
on:
  - push
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
      - name: pnpm
        run: npm i -g pnpm
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Test e2e
        run: pnpm test:e2e
