name: CI
run-name: CI with K6
on:
  - push
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
      - name: pnpm
        run: npm i -g pnpm
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Test e2e
        run: pnpm test:e2e

      # - name: Install k6
      #   run: |
      #     curl https://github.com/grafana/k6/releases/download/v0.44.0/k6-v0.44.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1 
      # - name: Start server and run tests
      #   run: |
      #     pnpm start & pnpx wait-on http://localhost:3000
      #     ./k6 run ./loadtest/loadtest.test.js

      # Only for example. Should test with real non-prod server.
      - name: Start the NestJS server
        run: |
          # Start the NestJS app in the background
          pnpm start &

          # Wait for the server to be ready (using curl to hit the health endpoint)
          until curl --silent --fail http://localhost:3000; do
            echo "Waiting for NestJS to start..."
            sleep 2
          done
          echo "NestJS is up and running!"

      - uses: grafana/setup-k6-action@v1
      - uses: grafana/run-k6-action@v1
        with:
          path: |
            ./loadtest/*.test.js

      - name: Stop the NestJS server (Optional)
        run: |
          # Kill the background NestJS process (if needed)
          pkill -f "pnpm start"
